def character(errors, word):
    if errors == 0:
        print(' _____ ')
        print(' |   | ')
        print(' |     ')
        print(' |     ')
        print(' |     ')
        print(' |     ')
        print('---    ')
    elif errors == 1:
        print(' _____ ')
        print(' |   | ')
        print(' |   o ')
        print(' |     ')
        print(' |     ')
        print(' |     ')
        print('---    ')
    elif errors == 2:
        print(' _____ ')
        print(' |   | ')
        print(' |   o ')
        print(' |   | ')
        print(' |     ')
        print(' |     ')
        print('---    ')
    elif errors == 3:
        print(' _____ ')
        print(' |   | ')
        print(' |   o ')
        print(' |   | ')
        print(' |  /  ')
        print(' |     ')
        print('---    ')
    elif errors == 4:
        print(' _____ ')
        print(' |   | ')
        print(' |   o ')
        print(' |   | ')
        print(' |  / \\')
        print(' |     ')
        print('---    ')
    elif errors == 5:
        print(' _____ ')
        print(' |   | ')
        print(' |   o ')
        print(' |  /| ')
        print(' |  / \\')
        print(' |     ')
        print('---    ')
    elif errors == 6:
        print(' _____ ')
        print(' |   | ')
        print(' |   o ')
        print(' |  /|\\')
        print(' |  / \\')
        print(' |     ')
        print('---    ')
        